import { createConversationSchema, sendMessageSchema, suggestTasksInputSchema } from "@contextos-ai/validators/ai";
import { breakdownGoalSchema } from "@contextos-ai/validators/task";
import { executeActionInputSchema } from "@contextos-ai/validators/ai-actions";
import { parseInput } from "@contextos-ai/validators/parse";
import type { RequestHandler } from "express";

import { prisma } from "@contextos-ai/database";
import { BadRequestError, NotFoundError, UnauthorizedError } from "../../lib/http-errors.js";
import { logger } from "../../lib/logger.js";
import { created, ok } from "../../lib/response.js";
import { aiProviderInstance, aiServiceInstance } from "./index.js";
import { actionExecutorService } from "./action-executor.service.js";

function requireUserId(req: Parameters<RequestHandler>[0]): string {
  if (!req.user) throw new UnauthorizedError();
  return req.user.id;
}

function requireParam(value: string | string[] | undefined, name: string): string {
  if (typeof value === "string" && value.length > 0) return value;
  throw new BadRequestError(`Missing path parameter: ${name}`);
}

// ──────────────────────────────────────────
// Conversations
// ──────────────────────────────────────────

export const listConversationsController: RequestHandler = async (req, res) => {
  const userId = requireUserId(req);
  const projectId = requireParam(req.params.projectId, "projectId");
  const conversations = await aiServiceInstance.listConversations(projectId, userId);
  const mapped = conversations.map(({ _count, ...rest }) => ({ ...rest, messageCount: _count.messages }));
  res.json(ok(mapped));
};

export const createConversationController: RequestHandler = async (req, res) => {
  const userId = requireUserId(req);
  const projectId = requireParam(req.params.projectId, "projectId");
  const input = parseInput(createConversationSchema, req.body);
  const { _count, ...rest } = await aiServiceInstance.createConversation(projectId, userId, input.title);
  res.status(201).json(created({ ...rest, messageCount: _count.messages }));
};

export const deleteConversationController: RequestHandler = async (req, res) => {
  const userId = requireUserId(req);
  const conversationId = requireParam(req.params.conversationId, "conversationId");
  await aiServiceInstance.deleteConversation(conversationId, userId);
  res.status(204).end();
};

// ──────────────────────────────────────────
// Messages
// ──────────────────────────────────────────

export const listMessagesController: RequestHandler = async (req, res) => {
  const userId = requireUserId(req);
  const conversationId = requireParam(req.params.conversationId, "conversationId");
  const messages = await aiServiceInstance.listMessages(conversationId, userId);
  res.json(ok(messages));
};

export const suggestTasksController: RequestHandler = async (req, res) => {
  const userId = requireUserId(req);
  const projectId = requireParam(req.params.projectId, "projectId");
  const { prompt } = parseInput(suggestTasksInputSchema, req.body);
  const tasks = await aiServiceInstance.suggestTasks(projectId, userId, prompt);
  res.json(ok({ tasks }));
};

/**
 * POST /projects/:projectId/conversations/breakdown-tasks — SSE streaming task breakdown.
 *
 * Accepts a high-level goal and streams structured task objects as they are
 * generated by the AI (NDJSON-parsed progressively from the Gemini stream).
 *
 * SSE events:
 *   { type: "task",  task: { title, description?, priority, status, estimatedEffort? } }
 *   { type: "done",  count: N }
 *   { type: "error", message: "..." }
 */
export const breakdownTasksController: RequestHandler = async (req, res) => {
  const userId = requireUserId(req);
  const projectId = requireParam(req.params.projectId, "projectId");
  const { goal } = parseInput(breakdownGoalSchema, req.body);

  const project = await prisma.project.findFirst({
    where: { id: projectId, ownerId: userId, deletedAt: null },
    select: {
      name: true,
      description: true,
      tasks: {
        where: { deletedAt: null },
        select: { title: true },
        take: 20,
        orderBy: { createdAt: "desc" },
      },
    },
  });
  if (!project) throw new NotFoundError("Project not found");

  const existingTaskTitles = project.tasks.map((t) => t.title);

  const generator = aiProviderInstance.streamBreakdown({
    projectName: project.name,
    projectDescription: project.description,
    existingTaskTitles,
    goal,
  });

  // Peek first value — triggers Gemini initialisation before SSE headers are sent
  // so errors (bad API key, quota exceeded) reach the standard JSON error handler.
  const first = await generator.next();

  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");
  res.setHeader("X-Accel-Buffering", "no");
  res.flushHeaders();

  let clientDisconnected = false;
  req.on("close", () => {
    clientDisconnected = true;
    logger.debug({ projectId }, "breakdown SSE client disconnected");
  });

  function sendEvent(data: object) {
    if (!clientDisconnected && !res.writableEnded) {
      res.write(`data: ${JSON.stringify(data)}\n\n`);
    }
  }

  const VALID_PRIORITIES = ["LOW", "MEDIUM", "HIGH", "URGENT"] as const;
  const VALID_STATUSES = ["TODO", "IN_PROGRESS", "REVIEW", "DONE"] as const;
  const VALID_ASSIGNEE_ROLES = [
    "Frontend Dev",
    "Backend Dev",
    "Full-Stack Dev",
    "DevOps",
    "Designer",
    "QA Engineer",
  ] as const;
  const VALID_CATEGORIES = ["frontend", "backend", "database", "testing", "deployment"] as const;
  const VALID_COMPLEXITIES = ["XS", "S", "M", "L", "XL"] as const;
  let lineBuffer = "";
  let taskCount = 0;

  function processChunk(text: string) {
    lineBuffer += text;
    const lines = lineBuffer.split("\n");
    lineBuffer = lines.pop() ?? "";
    for (const line of lines) {
      const trimmed = line.trim().replace(/,$/, "");
      if (!trimmed || trimmed === "[" || trimmed === "]") continue;
      try {
        const obj = JSON.parse(trimmed) as Record<string, unknown>;
        if (typeof obj.title !== "string" || !obj.title.trim()) continue;

        sendEvent({
          type: "task",
          task: {
            title: String(obj.title).slice(0, 200).trim(),
            description: obj.description ? String(obj.description).slice(0, 5000) : undefined,
            priority: VALID_PRIORITIES.includes(obj.priority as never) ? obj.priority : "MEDIUM",
            status: VALID_STATUSES.includes(obj.status as never) ? obj.status : "TODO",
            estimatedEffort: obj.estimatedEffort ? String(obj.estimatedEffort).slice(0, 50) : undefined,
            estimatedHours:
              typeof obj.estimatedHours === "number" && obj.estimatedHours > 0
                ? Math.min(Math.round(obj.estimatedHours), 40)
                : undefined,
            assigneeRole: VALID_ASSIGNEE_ROLES.includes(obj.assigneeRole as never)
              ? (obj.assigneeRole as string)
              : undefined,
            week:
              typeof obj.week === "number" && (obj.week === 1 || obj.week === 2)
                ? obj.week
                : undefined,
            dependencies: Array.isArray(obj.dependencies)
              ? (obj.dependencies as unknown[])
                  .filter((d): d is string => typeof d === "string")
                  .slice(0, 10)
                  .map((d) => d.slice(0, 200))
              : undefined,
            acceptanceCriteria: Array.isArray(obj.acceptanceCriteria)
              ? (obj.acceptanceCriteria as unknown[])
                  .filter((c): c is string => typeof c === "string")
                  .slice(0, 8)
                  .map((c) => c.slice(0, 300))
              : undefined,
            implementationNotes: obj.implementationNotes
              ? String(obj.implementationNotes).slice(0, 500)
              : undefined,
            category: VALID_CATEGORIES.includes(obj.category as never) ? obj.category : undefined,
            complexity: VALID_COMPLEXITIES.includes(obj.complexity as never) ? obj.complexity : undefined,
            suggestedDueDate:
              typeof obj.suggestedDueDate === "string" && /^\d{4}-\d{2}-\d{2}$/.test(obj.suggestedDueDate)
                ? obj.suggestedDueDate
                : undefined,
            sprintOrder:
              typeof obj.sprintOrder === "number" && obj.sprintOrder >= 1 && obj.sprintOrder <= 4
                ? Math.round(obj.sprintOrder)
                : undefined,
          },
        });
        taskCount++;
      } catch {
        // Unparseable line — skip silently; buffer may still be incomplete.
      }
    }
  }

  try {
    if (!first.done) {
      processChunk(first.value);
      for await (const chunk of generator) {
        processChunk(chunk);
      }
    }
    // Flush any remaining buffered content after the stream ends.
    if (lineBuffer.trim()) processChunk("\n");
    sendEvent({ type: "done", count: taskCount });
    if (!res.writableEnded) res.end();
  } catch (err) {
    logger.error({ err, projectId }, "breakdown SSE stream error after headers committed");
    if (!res.writableEnded) {
      sendEvent({ type: "error", message: "AI breakdown failed. Please try again." });
      res.end();
    }
  }
};

/**
 * POST /conversations/:conversationId/messages — streaming chat endpoint.
 *
 * Responds as SSE (text/event-stream). Each event is a JSON object:
 *   { "type": "chunk",  "content": "..." }     — partial AI text
 *   { "type": "done",   "userMessageId": "...", "aiMessageId": "..." }
 *   { "type": "error",  "message": "..." }      — fatal error mid-stream
 *
 * Errors BEFORE headers are sent propagate to the centralized error handler
 * (which sends a JSON 4xx/5xx). Errors AFTER streaming starts are sent as
 * an SSE error event so the client can react gracefully.
 */
export const streamChatController: RequestHandler = async (req, res) => {
  const userId = requireUserId(req);
  const conversationId = requireParam(req.params.conversationId, "conversationId");
  const input = parseInput(sendMessageSchema, req.body);

  // All validation happens before we start the stream so errors still go
  // through the normal error handler as JSON (no partial SSE response).
  const generator = aiServiceInstance.streamChat(conversationId, userId, input.content);

  // Peek the first value to trigger ownership validation before committing to SSE.
  // If validation throws, Express catches it and sends a proper error response.
  const first = await generator.next();

  // Headers committed — past this point all errors go via SSE.
  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");
  res.setHeader("X-Accel-Buffering", "no"); // Disable Nginx buffering.
  res.flushHeaders();

  // Track client disconnect so we stop writing to a closed socket.
  // We intentionally do NOT abort the generator — letting it run to completion
  // ensures the AI message is persisted to the DB even if the client left.
  // Aborting mid-stream would leave an orphaned user message with no AI reply.
  let clientDisconnected = false;
  req.on("close", () => {
    clientDisconnected = true;
    logger.debug({ conversationId }, "SSE client disconnected");
  });

  function sendEvent(data: object) {
    if (!clientDisconnected && !res.writableEnded) {
      res.write(`data: ${JSON.stringify(data)}\n\n`);
    }
  }

  try {
    if (!first.done) {
      sendEvent(first.value);

      for await (const event of generator) {
        sendEvent(event);
      }
    }
    if (!res.writableEnded) res.end();
  } catch (err) {
    logger.error({ err, conversationId }, "SSE stream error after headers committed");
    if (!res.writableEnded) {
      sendEvent({ type: "error", message: "AI service error. Please try again." });
      res.end();
    }
  }
};

/**
 * POST /conversations/:conversationId/execute-action
 *
 * Executes an AI-proposed action after the user confirms it in the UI.
 * Resolves projectId from the conversation row to enforce ownership.
 */
export const executeActionController: RequestHandler = async (req, res) => {
  const userId = requireUserId(req);
  const conversationId = requireParam(req.params.conversationId, "conversationId");
  const { action } = parseInput(executeActionInputSchema, req.body);

  const conversation = await prisma.aiConversation.findFirst({
    where: { id: conversationId, userId, deletedAt: null },
    select: { projectId: true },
  });
  if (!conversation) throw new NotFoundError("Conversation not found");

  const result = await actionExecutorService.execute(conversation.projectId, userId, action);

  logger.info(
    { conversationId, projectId: conversation.projectId, actionType: action.type },
    "execute-action: completed",
  );

  res.json(ok(result));
};
