import {
  prisma,
  type AiInsight,
  type InsightType,
  type InsightSeverity,
} from "@/database";

import type { AiProvider } from "../ai/ai.provider.js";
import { NotFoundError, ServiceUnavailableError } from "../../lib/http-errors.js";
import { logger } from "../../lib/logger.js";
import { buildInsightPrompt } from "./insight.prompts.js";
import { insightRepository } from "./insight.repository.js";

const CACHE_TTL_MS = 30 * 60 * 1000; // 30 minutes

type InsightStreamEvent =
  | { type: "chunk"; content: string }
  | { type: "done"; insightId: string; fromCache?: boolean };

/** Extract STATUS line from generated content and map to InsightSeverity. */
function inferSeverity(content: string): InsightSeverity {
  const lines = content.trim().split("\n");
  for (let i = 0; i < Math.min(lines.length, 4); i++) {
    const line = lines[i]?.trim() ?? "";
    if (line.startsWith("STATUS:")) {
      const val = line.replace("STATUS:", "").trim().toUpperCase();
      if (val === "CRITICAL") return "CRITICAL";
      if (val === "WARNING") return "WARNING";
      return "INFO";
    }
  }
  return "WARNING";
}

/** Confidence = ratio of non-empty sections (0–1). */
function inferConfidence(content: string): number {
  const sections = content.match(/^###/gm)?.length ?? 0;
  return Math.min(1, Math.max(0.3, sections / 5));
}

export function createInsightService(provider: AiProvider) {
  return {
    async listInsights(projectId: string, userId: string): Promise<AiInsight[]> {
      await requireProject(projectId, userId);
      return insightRepository.listForProject(projectId, userId);
    },

    async dismissInsight(
      projectId: string,
      type: InsightType,
      userId: string,
    ): Promise<AiInsight> {
      await requireProject(projectId, userId);
      const insight = await insightRepository.dismiss(projectId, type);
      if (!insight) throw new NotFoundError("Insight not found");
      return insight;
    },

    async undismissInsight(
      projectId: string,
      type: InsightType,
      userId: string,
    ): Promise<AiInsight> {
      await requireProject(projectId, userId);
      const insight = await insightRepository.undismiss(projectId, type);
      if (!insight) throw new NotFoundError("Insight not found");
      return insight;
    },

    async deleteInsight(
      projectId: string,
      type: InsightType,
      userId: string,
    ): Promise<void> {
      await requireProject(projectId, userId);
      await insightRepository.delete(projectId, type, userId);
    },

    async *generateInsight(
      projectId: string,
      type: InsightType,
      userId: string,
      options?: { autoGenerated?: boolean; force?: boolean },
    ): AsyncGenerator<InsightStreamEvent, void, undefined> {
      const project = await prisma.project.findFirst({
        where: { id: projectId, ownerId: userId, deletedAt: null },
        select: { name: true, description: true },
      });
      if (!project) throw new NotFoundError("Project not found");

      // Serve from 30-minute cache unless caller forces regeneration
      if (!options?.force) {
        const cached = await insightRepository.findByProjectAndType(projectId, type);
        if (cached && Date.now() - cached.updatedAt.getTime() < CACHE_TTL_MS) {
          yield { type: "chunk", content: cached.content };
          yield { type: "done", insightId: cached.id, fromCache: true };
          return;
        }
      }

      const rawTasks = await prisma.task.findMany({
        where: { projectId, deletedAt: null },
        select: {
          title: true,
          description: true,
          status: true,
          priority: true,
          dueDate: true,
          createdAt: true,
          updatedAt: true,
        },
        orderBy: [{ status: "asc" }, { priority: "asc" }, { position: "asc" }],
      });

      const tasks = rawTasks.map((t) => ({ ...t, assignees: [] as string[] }));

      const { systemPrompt, userMessage } = buildInsightPrompt(
        type,
        project.name,
        project.description,
        tasks,
      );

      let fullContent = "";

      try {
        const generator = provider.streamChat({
          history: [],
          userMessage,
          systemPrompt,
        });

        let iterResult = await generator.next();
        while (!iterResult.done) {
          const chunk = iterResult.value as string;
          fullContent += chunk;
          yield { type: "chunk", content: chunk };
          iterResult = await generator.next();
        }
      } catch (err) {
        logger.error(
          {
            err,
            projectId,
            insightType: type,
            geminiStatus: (err as Record<string, unknown>).status,
            geminiErrorDetails: (err as Record<string, unknown>).errorDetails,
          },
          "insight: AI stream failed",
        );
        throw new ServiceUnavailableError("AI provider error — check server logs");
      }

      const severity = inferSeverity(fullContent);
      const confidence = inferConfidence(fullContent);

      const insight = await insightRepository.upsert({
        projectId,
        type,
        content: fullContent,
        metadata: { generatedAt: new Date().toISOString(), taskCount: tasks.length },
        severity,
        confidence,
        autoGenerated: options?.autoGenerated ?? false,
      });

      yield { type: "done", insightId: insight.id };
    },
  };
}

async function requireProject(projectId: string, userId: string): Promise<void> {
  const project = await prisma.project.findFirst({
    where: { id: projectId, ownerId: userId, deletedAt: null },
    select: { id: true },
  });
  if (!project) throw new NotFoundError("Project not found");
}
