import {
  prisma,
  type AiInsight,
  type InsightType,
  type InsightSeverity,
} from "@/database";

export const insightRepository = {
  async listForProject(projectId: string, userId: string): Promise<AiInsight[]> {
    const project = await prisma.project.findFirst({
      where: { id: projectId, ownerId: userId, deletedAt: null },
      select: { id: true },
    });
    if (!project) return [];

    return prisma.aiInsight.findMany({
      where: { projectId },
      orderBy: [{ severity: "desc" }, { type: "asc" }],
    });
  },

  async listActiveForProject(projectId: string): Promise<AiInsight[]> {
    return prisma.aiInsight.findMany({
      where: { projectId, dismissedAt: null },
      orderBy: [{ severity: "desc" }, { updatedAt: "desc" }],
    });
  },

  async findByProjectAndType(projectId: string, type: InsightType): Promise<AiInsight | null> {
    return prisma.aiInsight.findUnique({
      where: { projectId_type: { projectId, type } },
    });
  },

  async upsert(data: {
    projectId: string;
    type: InsightType;
    content: string;
    metadata?: unknown;
    severity?: InsightSeverity;
    confidence?: number;
    autoGenerated?: boolean;
  }): Promise<AiInsight> {
    return prisma.aiInsight.upsert({
      where: { projectId_type: { projectId: data.projectId, type: data.type } },
      create: {
        projectId: data.projectId,
        type: data.type,
        content: data.content,
        metadata: (data.metadata as never) ?? undefined,
        severity: data.severity ?? "INFO",
        confidence: data.confidence ?? 0.5,
        autoGenerated: data.autoGenerated ?? false,
        dismissedAt: null,
      },
      update: {
        content: data.content,
        metadata: (data.metadata as never) ?? undefined,
        severity: data.severity ?? "INFO",
        confidence: data.confidence ?? 0.5,
        autoGenerated: data.autoGenerated ?? false,
        dismissedAt: null,
      },
    });
  },

  async dismiss(projectId: string, type: InsightType): Promise<AiInsight | null> {
    const insight = await prisma.aiInsight.findUnique({
      where: { projectId_type: { projectId, type } },
    });
    if (!insight) return null;

    return prisma.aiInsight.update({
      where: { projectId_type: { projectId, type } },
      data: { dismissedAt: new Date() },
    });
  },

  async undismiss(projectId: string, type: InsightType): Promise<AiInsight | null> {
    return prisma.aiInsight.update({
      where: { projectId_type: { projectId, type } },
      data: { dismissedAt: null },
    }).catch(() => null);
  },

  async delete(projectId: string, type: InsightType, userId: string): Promise<number> {
    const project = await prisma.project.findFirst({
      where: { id: projectId, ownerId: userId, deletedAt: null },
      select: { id: true },
    });
    if (!project) return 0;

    const result = await prisma.aiInsight.deleteMany({
      where: { projectId, type },
    });
    return result.count;
  },

  async countCriticalForUser(userId: string): Promise<number> {
    return prisma.aiInsight.count({
      where: {
        project: { ownerId: userId, deletedAt: null },
        severity: "CRITICAL",
        dismissedAt: null,
      },
    });
  },
};
