import { z } from "zod";

import { cuidSchema } from "./primitives";

// ============== Insight type enum + param schema ==============

export const insightTypeEnum = z.enum([
  // Core (manual generation)
  "NEXT_TASK",
  "OVERDUE_TASKS",
  "DAILY_SUMMARY",
  "WORKLOAD_PRIORITY",
  "BLOCKER_DETECTION",
  "SPRINT_IMPROVEMENTS",
  "WEEKLY_SUMMARY",
  // Automation-triggered
  "OVERDUE_RECOVERY",
  "INACTIVE_PROJECT",
  "BLOCKED_WORKFLOW",
  "PRODUCTIVITY_SLOWDOWN",
  "SPRINT_RISK",
  "OVERLOAD_WARNING",
  "STALE_CONTENT",
  // Deep intelligence
  "DEPENDENCY_ANALYSIS",
  "BLOCKER_CHAIN",
  "SPRINT_FORECAST",
  "DELAY_IMPACT",
  "WORKLOAD_IMBALANCE",
  "STALL_ANALYSIS",
  "CRITICAL_PATH",
]);
export type InsightType = z.infer<typeof insightTypeEnum>;

export const CORE_INSIGHT_TYPES: InsightType[] = [
  "NEXT_TASK",
  "OVERDUE_TASKS",
  "DAILY_SUMMARY",
  "WORKLOAD_PRIORITY",
  "BLOCKER_DETECTION",
  "SPRINT_IMPROVEMENTS",
  "WEEKLY_SUMMARY",
];

export const AUTOMATION_INSIGHT_TYPES: InsightType[] = [
  "OVERDUE_RECOVERY",
  "INACTIVE_PROJECT",
  "BLOCKED_WORKFLOW",
  "PRODUCTIVITY_SLOWDOWN",
  "SPRINT_RISK",
  "OVERLOAD_WARNING",
  "STALE_CONTENT",
];

export const DEEP_INSIGHT_TYPES: InsightType[] = [
  "DEPENDENCY_ANALYSIS",
  "BLOCKER_CHAIN",
  "SPRINT_FORECAST",
  "DELAY_IMPACT",
  "WORKLOAD_IMBALANCE",
  "STALL_ANALYSIS",
  "CRITICAL_PATH",
];

export const insightSeverityEnum = z.enum(["INFO", "WARNING", "CRITICAL"]);
export type InsightSeverity = z.infer<typeof insightSeverityEnum>;

export const insightTypeParamSchema = z.object({ type: insightTypeEnum });

// ============== SSE stream events ==============

export const insightStreamChunkEvent = z.object({ type: z.literal("chunk"), content: z.string() });
export const insightStreamDoneEvent = z.object({
  type: z.literal("done"),
  insightId: cuidSchema,
  fromCache: z.boolean().optional(),
});
export const insightStreamErrorEvent = z.object({ type: z.literal("error"), message: z.string() });

export const insightStreamEvent = z.discriminatedUnion("type", [
  insightStreamChunkEvent,
  insightStreamDoneEvent,
  insightStreamErrorEvent,
]);
export type InsightStreamEvent = z.infer<typeof insightStreamEvent>;

// ============== Insight DTO ==============

export const insightDTO = z.object({
  id: cuidSchema,
  projectId: cuidSchema,
  type: insightTypeEnum,
  content: z.string(),
  metadata: z.unknown().nullable(),
  severity: insightSeverityEnum,
  confidence: z.number(),
  autoGenerated: z.boolean(),
  dismissedAt: z.coerce.date().nullable(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
});
export type InsightDTO = z.infer<typeof insightDTO>;
